r-lib/pak

R/package.R
But the directly specified `pkg` needs to
be (re)installed.
E.g. 
```
pkg_install("r-lib/crayon")
pkg_install("cran::crayon")
```
The second should reinstall `crayon` from CRAN.
=> Fix pkg_install when no deps are installed

R/package.R, R/utils.R, tests/testthat/test-package.R
Looks like this now:
```
❯ pkg_install(c("dplyr", "purrr"), lib = "/tmp/lib/")
Updating CRAN metadata
✔ CRAN metadata current
✔ Found 34 dependencies for 2 packages in 575ms
✔ No downloads are needed
✔ dplyr 0.7.4 and 13 dependencies already installed
✔ purrr 0.2.4 and 5 dependencies already installed
```
=> Improve output when no installs needed

R/package.R
Closes #33 
When a `solve()` fails:
```
❯ pkg_install(c("r-lib/usethis", "cran::usethis"))
Updating CRAN metadata
✔ CRAN metadata current
✔ Found 62 dependencies for 2 packages in 1.6s
Error: Cannot install packages:
* Cannot install package `usethis`.
- `cran::usethis`, conflicts with `r-lib/usethis`
- `installed::/Users/gaborcsardi/r_pkgs/usethis`, conflicts with `r-lib/usethis`
- `r-lib/usethis`, conflicts with `cran::usethis`
```
or when a download fails:
```
❯ pkg_install("r-lib/usethis", lib = "/tmp/lib")
Updating CRAN metadata
✔ Updated CRAN metadata
✔ Found 23 dependencies for 1 packages in 2.9s
✔ 38 packages, in 6.5s
Error: Cannot download some packages:
Failed to download Rcpp from `https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/Rcpp_0.12.14.tgz`.
Failed to download …
```
=> pkg_install throws proper errors

DESCRIPTION
fixes pkgdepends::remotes$new("r-lib/pkgman") fails with `Error: invalid version specification ‘NA’` when solve()ing. Tracking down shows async is improperly given a standard ref as no remote specified.
=> add remote ref for async

R/subprocess.R
The pak counterpoint to https://github.com/r-lib/pkgdepends/pull/196
An alternative to this is to have pkgdepends respect the `R_PKG_SHOW_PROGRESS` envvar, which we are already setting in the subprocess...
=> Pass `pkg.show_progress` down to the subprocess

DESCRIPTION
There is only 1.3-2, not 1.3.2.
I'm not sure if R treats these the same exactly, but it causes confusion in downstream packaging.
=> Fix version of rprojroot dependency.

DESCRIPTION, R/system-requirements.R, man/local_system_requirements.Rd
=> Automatically lookup the operating system and release version

DESCRIPTION, R/confirmation.R, R/local.R, R/package.R, R/print.R, R/terminate.R, R/unload.R, R/utils.R, R/warn-loaded.R
(In the same session.)
Closes #174
=> Warn for installing loaded packages

DESCRIPTION
https://cran.r-project.org/package=distro
so you don't need Remotes to get it anymore
=> distro is now on CRAN

R/system-requirements.R, man/local_system_requirements.Rd
* Improve docs
* Only return invisibly when executing
=> System requirement tweaks

R/package.R
I think this should not be there.
=> tyepo - remove backtick in example

DESCRIPTION
Stumbled across this while doing some analysis needed to make usethis better recognizing RStudio-associated packages.
This PR makes the fix and formats `Authors@R` the way `use_tidy_description()` does.
=> Fix RStudio's listing in Authors@R

R/package.R, man/local_install.Rd, man/local_install_deps.Rd, man/local_install_dev_deps.Rd, man/lockfile_create.Rd, man/pkg_install.Rd
=> Fix typo in `pkg_install` documentation.

man/chunks/FAQ.Rmd
The existing example causes the following warning to be generated in the docs:
```R
#> ! Unknown package parameter: "" in "formattable?=ignore". 
```
I assume this wasn't deliberate since the surrounding text doesn't mention it. I haven't recompiled the documentation since this is just a drive-by edit in the browser.
=> Fix syntax error in docs for optional dependency

R/onload.R
add behaviour to not overwrite option `async_http_cainfo` if set.
Closes #427
=> do not overwrite cainfo option

R/system-requirements.R, tests/testthat/test-system-requirements.R
Ideally, the server would do this for us. This is a kludge to speed up installation on Ubuntu while we're getting there.
Deliberately not optimizing for other distros yet, because Ubuntu is by far the most common case (GHA install).
=> Bundle apt-get install commands

R/search.R
Fix #505 
This is an attempt to fix the issue.
Let me know how to add tests.
My ad-hoc testing was 
```r
pkg_search("gist")
pkg_search("git")
pkg_search("git", from = 2)
pkg_search("gist", from = 2)
pkg_search("git", from = 2, size = 9)
pkg_search("gist", from = 5)
x No result. :(
pkg_search("git", from = 50)
```
=> Add size control in `pkg_search()`

R/search.R
I don't want to commit the redoc, but somehow, the fact that pkgsearch is not needed for that function can make it useful to enumerate the two additional args from pkgsearch..
```r
\item{...}{
Arguments passed on to \code{\link[pkgsearch:pkg_search]{pkgsearch::pkg_search}}
\describe{
\item{\code{from}}{Where to start listing the results, for pagination.}
\item{\code{size}}{The number of results to list.}
}}
```
=> Enumerate additional arguments in pkg_search

man/chunks/FAQ.Rmd, man/faq.Rd
Not sure why this typo no longer appears in `README.md` .
=> Fix typo in README

man/chunks/FAQ.Rmd, man/faq.Rd
I noticed that the FAQ about using pak in renv is out of date (as you know it's been possible for quite a while)
<https://pak.r-lib.org/reference/faq.html#how-can-i-use-pak-with-renv->
(Nb. For the second commit here, when I clicked *Document* in the RStudio Build pane in addition to faq.Rd alot of other files were amended - so I just selected the changes in that for this PR.)
=> Small suggestion - update FAQ about using pak with renv

R/system-requirements.R
Hello,
I know that the function is deprecated, but the documentation indicated that Debian was supported when it isn't.
=> remove debian from supported version

DESCRIPTION, R/sysreqs.R, man/pkg_sysreqs.Rd
This is the second time I've had to figure this out in order to generate a working example on my laptop, so I figured I'd actually document it. I couldn't get the documentation to build correctly and I'm not sure what style you use for these documentation helper functions, so you'll need to do a little work to finish it off.
=> List known platforms in `pkg_sysreqs()` documentation

tools/build/linux/Dockerfile, tools/build/linux/Dockerfile-libs, tools/build/linux/Dockerfile-libs-aarch64, tools/build/linux/Makefile
=> Linux: update dependencies in static build

src/library/pkgdepends/R/zzz-pkgdepends-config.R
Super tiny - I noticed some typos in a sentence on <https://pak.r-lib.org/reference/pak-config.html#pak-configuration-entries> for `sysreqs_db_update`.
=> Fix 2 typos in docs

src/library/pkgdepends/R/install-binary.R
When `options(install.lock = FALSE)` is set in `.Rprofile`, an error will be thrown when a package is successfully installed:
```
Error:                                           
! error in pak subprocess
Caused by error in `filelock::unlock(lockfile)`:
! `unlock()` needs a lock object, not a file name
```
This will abort the installation of other packages.
<hr>
In `install-binary.R`, `lock_cache` will return `NULL` if `getOption("install.lock")==FALSE`, which is not a valid parameter for `filelock::unlock` :
https://github.com/r-lib/pak/blob/2c8de25e1206a8c78b867df4dc28408e72ab4c7c/src/library/pkgdepends/R/install-binary.R#L9-L10
https://github.com/r-lib/pak/blob/2c8de25e1206a8c78b867df4dc28408e72ab4c7c/src/library/pkgdepends/R/install-utils.R#L58-L67 …
=> Avoid unlocking NULL

man/chunks/install.Rmd, man/install.Rd
A tiny amend of _CRAN release of CRAN_ to _CRAN release of pak_.
=> Amend accidentally repeated word in docs
