r-lib/pak

- R/package.R
- man/pkg_install.Rd
> upgrade option in pkg_install

- R/utils.R
Changed in pkgdepends, as well as in pkginstall (in a PR).
> pkg.progress.bar -> pkg.show_progress option

- R/confirmation.R
> Small typo

- DESCRIPTION
I certainly shouldn't be first, you have done much more work than I on this! Plus this way it is alphabetical 😉
> Make Gábor the first author

- R/pak-install.R
- R/private-lib.R
* Only asks to create directory if it doesn't exist
* Only report when packages are copied
* Display all packages on one line
Fixes #105. Fixes #113
(Fast tracking this since due to #103, I'm running this multiple times per day)
> Minimise pak_setup() messaging

- R/pak-cleanup.R
> pak_cleanup_lib should return FALSE for embedded libraries

- R/private-lib.R
We need to specify the library as the embedded one so that pak works
with the installer.
Fixes #193
> Specify the library for private packages in embedded mode

- R/system-requirements.R
- man/local_system_requirements.Rd
This can simplify use of pak in GitHub Actions and other CI systems.
> Allow execution of system arguments directly

- R/onload.R
- R/rstudio-detect.R
- R/subprocess.R
- R/utils.R
> Detect dynamic tty in the main process

- R/errors.R
- R/subprocess.R
> Don't show error call

- R/local.R
- R/pak.R
- man/pak.Rd
A couple of minor behaviour tweaks
> pak::pak() tweaks

- R/deps-explain.R
- R/local.R
- R/package.R
- man/local_deps.Rd
- man/local_deps_explain.Rd
- man/pkg_deps.Rd
- man/pkg_deps_explain.Rd
- man/pkg_deps_tree.Rd
- local_deps()
- local_deps_tree()
- local_dev_deps()
- local_dev_deps_tree()
- local_deps_explain()
- local_dev_deps_explain()
- pkg_deps()
- pkg_deps_explain()
- pkg_deps_tree()
> Add upgrade argument to deps() fucntions

- DESCRIPTION
- R/system-requirements.R
- man/handle_package_not_found.Rd
- man/local_system_requirements.Rd
- man/pak_package_sources.Rd
- man/pkg_name_check.Rd
As discussed in #327
Documentation and examples improved also in view of https://github.com/r-lib/pak/issues/315#issuecomment-954785543, for which the code now also handles corresponding API errors.
See individual commits for details.
> System requirements for multiple pkgs (+ error handling)

- man/chunks/tldr.Rmd
Fix typo in argument name of `pkg_install()`
> update -> upgrade in tldr vignette

- R/subprocess.R
Fixes https://github.com/rstudio/renv/issues/1628
Fixes #325.
> No .Rprofile if in renv

- man/chunks/FAQ.Rmd
> Fix typo in FAQ

- .github/workflows/nightly.yaml
- DESCRIPTION
- R/push-packages.R
- tools/build/macos/Makefile
- tools/build/windows/Makefile
To make the build process faster. Right now Windows is the slowest, taking about an hour.
> GHA: run multiple windows jobs

- DESCRIPTION
- R/mocks.R
- tests/testthat/test-platform.R
- tests/testthat/test-repo.R
Closes: https://github.com/r-lib/pak/issues/664
> tests: migrate to testthat mocking

- .github/workflows/pkgdown.yaml
> Fix dynamic code in pkgdown site

- man/chunks/auth.Rmd
- man/repo-auth.Rd
I noticed these while reading the auth docs
> Fixes for a few small typos
